### ISSUE TITLE
SA6400 with DSM7.2.1-69057 Update 3

### ISSUE THREAD

**Issue by error105** [wirgen/synocodectool-patch#10]
Hi, i have installed SA6400 with DSM7.2.1-69057 Update 3 on my N100 CPU. Everythink works fine, im install AME and after that im trying install that patch, it install proper but still i dont have AME 3.1.0 activated :(
Whats im make wrong?

**Comment by wirgen** [comment]
Visually, nothing changes in it, but transcoding works. Tested on generating image thumbnails and viewing videos from the file manager

**Comment by error105** [comment]
Hmmm, but i don’t see stream from H265 in SS, so I guess it won’t work :(
